In [1]:
!pip install pandas scikit-learn nltk

Requirement already satisfied: pandas in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: nltk in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: click in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [1]:
!pip install pandas scikit-learn nltk matplotlib seaborn

Requirement already satisfied: pandas in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: scikit-learn in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: nltk in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: matplotlib in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: click in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\503403283\appdata\local\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [1]:
import os
os.getcwd()

'C:\\Users\\503403283\\Documents\\Jupyter notebooks'

In [2]:
import pandas as pd

data = pd.read_excel('customer_tickets.xlsx')
data.head()

                        ticket_text   category
0      “My internet is not working”  technical
1  “I was charged twice this month”    billing
2              "App is not working"   business

In [3]:
data.columns  # lists all column names
data.info()   # checks for missing values and types
data.head()   # shows first 5 rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ticket_text  3 non-null      object
 1   category     3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes

                        ticket_text   category
0      “My internet is not working”  technical
1  “I was charged twice this month”    billing
2              "App is not working"   business

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

# Download NLTK packages
nltk.download('punkt')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = text.lower()  # lowercase
    text = re.sub(r'\W', ' ', text)  # remove special characters
    words = word_tokenize(text)  # split into words
    words = [w for w in words if w not in stop_words]  # remove stopwords
    return ' '.join(words)

data['clean_text'] = data['ticket_text'].apply(preprocess)
data.head()

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(data['clean_text'])
y = data['category']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

In [6]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

# Download necessary NLTK data (only needed once)
nltk.download('punkt')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = text.lower()  # lowercase
    text = re.sub(r'\W', ' ', text)  # remove special characters
    words = word_tokenize(text)  # split into words
    words = [w for w in words if w not in stop_words]  # remove stopwords
    return ' '.join(words)

[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>
[nltk_data] Error loading stopwords: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>

LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - 'C:\\Users\\503403283/nltk_data'
    - 'C:\\Users\\503403283\\AppData\\Local\\anaconda3\\nltk_data'
    - 'C:\\Users\\503403283\\AppData\\Local\\anaconda3\\share\\nltk_data'
    - 'C:\\Users\\503403283\\AppData\\Local\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\503403283\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [ ]:
new_ticket = ["I cannot log in to my account"]
new_ticket_clean = [preprocess(text) for text in new_ticket]
new_ticket_vec = vectorizer.transform(new_ticket_clean)
prediction = model.predict(new_ticket_vec)
print("Predicted category:", prediction[0])

In [ ]:
test_tickets = [
    "I cannot log in to my account",        # Technical
    "I was charged twice this month",       # Billing
    "How do I change my password?",         # Account
    "My internet keeps dropping",           # Technical
    "I want to update my billing info"      # Billing
]

# Preprocess
test_tickets_clean = [preprocess(text) for text in test_tickets]

# Convert to vector
test_tickets_vec = vectorizer.transform(test_tickets_clean)

# Predict
predictions = model.predict(test_tickets_vec)

# Display results
for ticket, category in zip(test_tickets, predictions):
    print(f"Ticket: {ticket} -> Predicted Category: {category}")

In [7]:
import pandas as pd
data = pd.read_excel('customer_tickets.xlsx')
data.head()

                        ticket_text   category
0      “My internet is not working”  technical
1  “I was charged twice this month”    billing
2              "App is not working"   business

In [8]:
import pandas as pd
data = pd.read_excel('customer_tickets.xlsx')
data.head()

                        ticket_text   category
0      “My internet is not working”  technical
1  “I was charged twice this month”    billing
2              "App is not working"   business
3     "How do I change my password"    account
4   "I want to update billing info"    billing

In [9]:
import pandas as pd
data = pd.read_excel('customer_tickets.xlsx')
data.head()

                        ticket_text   category
0      “My internet is not working”  technical
1  “I was charged twice this month”    billing
2              "App is not working"   business
3     "How do I change my password"    account
4   "I want to update billing info"    billing

In [10]:
pd.set_option('display.max_rows', None)
data

                         ticket_text   category
0       “My internet is not working”  technical
1   “I was charged twice this month”    billing
2               "App is not working"   business
3      "How do I change my password"    account
4    "I want to update billing info"    billing
5  "I cannot log in into my account"  technical

In [11]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

nltk.download('punkt')
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = text.lower()
    text = re.sub(r'\W', ' ', text)
    words = word_tokenize(text)
    words = [w for w in words if w not in stop_words]
    return ' '.join(words)

data['clean_text'] = data['ticket_text'].apply(preprocess)

[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>
[nltk_data] Error loading stopwords: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>

LookupError:
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')

  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - 'C:\\Users\\503403283/nltk_data'
    - 'C:\\Users\\503403283\\AppData\\Local\\anaconda3\\nltk_data'
    - 'C:\\Users\\503403283\\AppData\\Local\\anaconda3\\share\\nltk_data'
    - 'C:\\Users\\503403283\\AppData\\Local\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\503403283\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(data['clean_text'])
y = data['category']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = MultinomialNB()
model.fit(X_train, y_train)

In [12]:
test_tickets = [
    "I cannot log in into my account",
    "I was charged twice this month",
    "How do I change my password?",
    "My internet is not working",
    "I want to update billing info",
    "App is not working"
]

test_tickets_clean = [preprocess(text) for text in test_tickets]
test_tickets_vec = vectorizer.transform(test_tickets_clean)
predictions = model.predict(test_tickets_vec)

for ticket, category in zip(test_tickets, predictions):
    print(f"Ticket: {ticket} -> Predicted Category: {category}")

NameError: name 'preprocess' is not defined